class TIcons {
  static const String dashboardCustomer = "assets/icons/contact.svg";
  static const String dashboardProduct = "assets/icons/product.svg";
  static const String dashboardQROrder = "assets/icons/qr-order.svg";
  static const String dashboardReport = "assets/icons/report.svg";
  static const String dashboardSettings = "assets/icons/settings.svg";

  static const String bell = "assets/icons/bell.svg";
  static const String homeLock = "assets/icons/home-lock.svg";
  static const String warning = "assets/icons/warning.svg";
  static const String check = "assets/icons/check.svg";
  static const String bag = "assets/icons/bag.svg";
  static const String hamburgerMenu = "assets/icons/hamburger-menu.svg";
  static const String cashier = "assets/icons/cashier.svg";
  static const String lock = "assets/icons/lock.svg";
  static const String calendar = "assets/icons/calendar.svg";
  static const String filter = "assets/icons/filter.svg";
  static const String camera = "assets/icons/camera.svg";
  static const String download = "assets/icons/download.svg";
  static const String map = "assets/icons/map.svg";
  static const String arrowRight = "assets/icons/arrow-right.svg";
  static const String arrowLeft = "assets/icons/arrow-left.svg";
  static const String arrowDown = "assets/icons/arrow-down.svg";
  static const String graphStatsAscend = "assets/icons/graph-stats-ascend.svg";
  static const String graphStatsDescend =
      "assets/icons/graph-stats-descend.svg";
  static const String search = "assets/icons/search.svg";
  static const String bill = "assets/icons/bill.svg";
  static const String billAlt = "assets/icons/bill-alt.svg";
  static const String profile = "assets/icons/profile.svg";
  static const String trash = "assets/icons/trash.svg";
  static const String add = "assets/icons/add.svg";
  static const String minus = "assets/icons/minus.svg";
  static const String box = "assets/icons/box.svg";
  static const String image = "assets/icons/image.svg";
  static const String qr = "assets/icons/qr.svg";
  static const String close = "assets/icons/close.svg";
  static const String whatsapp = "assets/icons/whatsapp.svg";
  static const String contactBook = "assets/icons/contact-book.svg";
  static const String coinMultiple = "assets/icons/coin-multiple.svg";
  static const String tableRestaurant = "assets/icons/table-restaurant.svg";
  static const String moneyBill = "assets/icons/money-bill.svg";
  static const String moneyBillTransfer =
      "assets/icons/money-bill-transfer.svg";
  static const String creditCard = "assets/icons/credit-card.svg";
  static const String billChecked = "assets/icons/bill-check.svg";
  static const String grid = "assets/icons/grid.svg";
  static const String scanner = "assets/icons/scanner.svg";
  static const String cardIn = "assets/icons/card-in.svg";
  static const String billCross = "assets/icons/bill-cross.svg";

  static const String card = "assets/icons/card.svg";
  static const String filters = "assets/icons/filters.svg";
  static const String handMoney = "assets/icons/hand-money.svg";
  static const String linkSquare = "assets/icons/link-square.svg";
  static const String pieChart = "assets/icons/pie-chart.svg";
  static const String printer = "assets/icons/printer.svg";
  static const String smartphoneUpdate = "assets/icons/smartphone-update.svg";
  static const String userId = "assets/icons/user-id.svg";
  static const String eye = "assets/icons/eye.svg";
  static const String eyeClose = "assets/icons/eye-close.svg";
  static const String wallet = "assets/icons/wallet.svg";
  static const String document = "assets/icons/document.svg";
  static const String star = "assets/icons/star.svg";
  static const String shieldKeyhole = "assets/icons/shield-keyhole.svg";
  static const String roundGraph = "assets/icons/round-graph.svg";
  static const String pieChartOutline = "assets/icons/pie-chart-outline.svg";
  static const String billCheckedOutline =
      "assets/icons/bill-check-outline.svg";
  static const String cardTransfer = "assets/icons/card-transfer.svg";
  static const String letterOutline = "assets/icons/letter-outline.svg";
  static const String passwordOutline = "assets/icons/password-outline.svg";
  static const String smartphoneOutline = "assets/icons/smartphone-outline.svg";
  static const String userOutline = "assets/icons/user-outline.svg";
  static const String backspace = "assets/icons/backspace.svg";
  static const String refresh = "assets/icons/refresh.svg";
  static const String bluetooth = "assets/icons/bluetooth.svg";
  static const String infinity = "assets/icons/infinity.svg";
}
