name: dio_provider
description: Dart package which manages the dio.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  point_of_sales_cashier:
    path: ../../
