name: dio_provider
description: Dart package which manages the dio.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  app_config_provider:
    path: ../app_config_provider

  dio: ^5.6.0
  flutter:
    sdk: flutter
