name: dio_provider
description: Dart package which manages the dio.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  app_config_provider:
    path: ../app_config_provider
  
  flutter:
    sdk: flutter
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logman: ^0.0.21
  connectivity_plus: ^6.0.5
dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lakoe_pos:
    path: ../../
