name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  # providers
  token_provider:
    path: ../token_provider
  dio_provider:
    path: ../dio_provider
  app_data_provider:
    path: ../app_data_provider

  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lakoe_pos:
    path: ../../
