name: app_data_provider
description: Dart package which manages the application data.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2
