name: cashier_repository
description: Dart package which manages the owner domain.
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"
dependencies:
  # repositories
  customer_repository:
    path: ../customer_repository
  order_repository:
    path: ../order_repository

  # providers
  token_provider:
    path: ../token_provider
  dio_provider:
    path: ../dio_provider

  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
